import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar/NavBar";
import { AuthProvider } from "../context/AuthContext";
/* import { Providers } from "./providers/Providers"; */
import Footer from "./components/Footer/Footer";
/* import { Providers } from "./providers/Providers"; TODO: eliminar cuando ya tengamos el del back*/ 
import { CartProvider } from "../context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer/>
          </AuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
